    %       % 1. ON/OFF
    %       % 2. Relative First Activation time
    %       % 3. Relative Last Activation time
    %       % 4. Relative Total active duration
    %       % 5. Relative Total spot duration of existence 
    %       % 6. Relative Time to max intensity
    %       % 7. Brightest spot intensity
    %       % 8. Mean RNA produced
    %       % 9. Total RNA produced
    %       % 10. Total interphase duration
    %       % 11. Absolute First Activation time
    %       % 12. Absolute Last Activation time
    %       % 13. Absolute Total active duration
    %       % 14. Absolute Total spot duration of existence 
    %       % 15. Absolute Time to max intensity
Nfea=15;
feature_label={'ON',...
    't_{init}%',...
    't_{end}%',...
    't_{active}%',...
    't_{exist}%',...
    't_{max}%',...
    'max Ispot',...
    '\mu{I}',...
    '\Sigma{I}',...
    'tphase',...
    't_{init}',...
    't_{end}',...
    't_{active}',...
    't_{exist}',...
    't_{max}',...
    };
save('feature_label.mat','feature_label','Nfea');